"""Sentinel Collection 3 stage 3: extract training samples.

This script samples pixels from the segment masks exported by stage 2 and
joins them with Sentinel-2 spectral features plus annual Google Satellite
Embedding bands. The result is a per-grid, per-year training table exported
to Earth Engine assets.

Inputs:
- Sentinel-2 mosaic collections filtered by biome and mosaic version
- Segment-mask assets generated by stage 2
- `GOOGLE/SATELLITE_EMBEDDING/V1/ANNUAL` for each year in `YEARS`

Outputs:
- Training table assets under `.../SAMPLES/AMAZONIA/TRAINED`

Run this after stage 2 and before stage 4. This script skips assets already
present in the output folder, so version constants and year lists should be
changed carefully.
"""
import ee
from pprint import pprint

ee.Initialize(project='mapbiomas-colombia')

ASSET_MOSAICS = [
    'projects/nexgenmap/MapBiomas2/SENTINEL/mosaics-3',
    'projects/mapbiomas-mosaics/assets/SENTINEL/BRAZIL/mosaics-3'
    ]

ASSET_SEGMENTS = 'projects/mapbiomas-brazil/assets/LAND-COVER-10M/COLLECTION-3/SAMPLES/AMAZONIA/SEGMENTS'

ASSET_OUTPUT = 'projects/mapbiomas-brazil/assets/LAND-COVER-10M/COLLECTION-3/SAMPLES/AMAZONIA/TRAINED'

EMBEDDING_COLLECTION = ee.ImageCollection('GOOGLE/SATELLITE_EMBEDDING/V1/ANNUAL')

YEARS = [
    2025,
    2024,
    2023,
    2022,
    2021,
    2020,
    2019,
    2018,
    2017,
    # 2016, # ainda nao tem embedding
]

N_SAMPLES = 1000

MOSAIC_VERSION = '3'

SEGMENTS_VERSION = '1'

# versao 1 - 1000 amostras sorteadas no mapa estavel segmenmtadas + embedding
OUTPUT_VERSION = '1'

FACTOR_SAMPLES = 0.003

GRID_NAMES = []

FEAT_SPACE_BANDS = [
    "blue_median", 
    "blue_median_wet", 
    "blue_median_dry", 
    "blue_stdDev",
    "green_median", 
    "green_median_dry", 
    "green_median_wet", 
    "green_median_texture",
    "green_min", 
    "green_stdDev",
    "red_median", 
    "red_median_dry", 
    "red_min", 
    "red_median_wet", 
    "red_stdDev",
    "nir_median", 
    "nir_median_dry", 
    "nir_median_wet", 
    "nir_stdDev",
    "red_edge_1_median",
    "red_edge_1_median_dry", 
    "red_edge_1_median_wet", 
    "red_edge_1_stdDev",
    "red_edge_2_median",
    "red_edge_2_median_dry", 
    "red_edge_2_median_wet", 
    "red_edge_2_stdDev",
    "red_edge_3_median",
    "red_edge_3_median_dry", 
    "red_edge_3_median_wet", 
    "red_edge_3_stdDev",
    "red_edge_4_median",
    "red_edge_4_median_dry", 
    "red_edge_4_median_wet", 
    "red_edge_4_stdDev",
    "swir1_median", 
    "swir1_median_dry", 
    "swir1_median_wet", 
    "swir1_stdDev",
    "swir2_median", 
    "swir2_median_wet", 
    "swir2_median_dry", 
    "swir2_stdDev"
]

EMBEDDING_BANDS = [
  "A00",
  "A01",
  "A02",
  "A03",
  "A04",
  "A05",
  "A06",
  "A07",
  "A08",
  "A09",
  "A10",
  "A11",
  "A12",
  "A13",
  "A14",
  "A15",
  "A16",
  "A17",
  "A18",
  "A19",
  "A20",
  "A21",
  "A22",
  "A23",
  "A24",
  "A25",
  "A26",
  "A27",
  "A28",
  "A29",
  "A30",
  "A31",
  "A32",
  "A33",
  "A34",
  "A35",
  "A36",
  "A37",
  "A38",
  "A39",
  "A40",
  "A41",
  "A42",
  "A43",
  "A44",
  "A45",
  "A46",
  "A47",
  "A48",
  "A49",
  "A50",
  "A51",
  "A52",
  "A53",
  "A54",
  "A55",
  "A56",
  "A57",
  "A58",
  "A59",
  "A60",
  "A61",
  "A62",
  "A63"
]

collection = (
    ee.ImageCollection(ASSET_MOSAICS[0]).merge(ee.ImageCollection(ASSET_MOSAICS[1]))
    .filter(ee.Filter.eq('version', MOSAIC_VERSION))
    .filter(ee.Filter.eq('biome', 'AMAZONIA'))
    )

print(collection.size().getInfo())

if len(GRID_NAMES) == 0:
    # Empty GRID_NAMES means "discover all available grids from the mosaics".
    GRID_NAMES = collection.aggregate_histogram('grid_name').getInfo().keys()

print(GRID_NAMES)

# TRAINED holds table (FeatureCollection) assets, not an ImageCollection,
# so existing outputs are enumerated via the asset listing API instead.
alreadyInCollection = [
    asset['name'].split('/')[-1]
    for asset in ee.data.listAssets({'parent': ASSET_OUTPUT})['assets']
]

for year in YEARS:

    collectionYear = collection.filterMetadata('year', 'equals', year)

    # The annual embedding image is appended as extra predictors for sampling.
    embeddingImage = ee.Image(EMBEDDING_COLLECTION
      .filterDate(f'{year}-01-01', f'{year}-12-31')
      .mosaic())

    for gridName in GRID_NAMES:

        samplesName = '{}-{}-{}'.format(gridName, year, OUTPUT_VERSION)

        # Avoid resubmitting exports that are already present in the TRAINED folder.
        if samplesName in alreadyInCollection:
            continue

        try:

            image = collectionYear.filter(
                ee.Filter.eq('grid_name', gridName)).first()

            image = ee.Image(image)
            
            composite = image.addBands(embeddingImage)

            region = image.geometry()

            similarMask = ee.Image('{}/{}-SEGMENTS-{}-{}-{}'.format(
                ASSET_SEGMENTS, gridName, year, N_SAMPLES, SEGMENTS_VERSION))

            # Sample only inside labeled segments propagated from stable references.
            composite = composite.mask(similarMask.neq(0))

            samples = composite\
                .select(FEAT_SPACE_BANDS + EMBEDDING_BANDS)\
                .addBands(similarMask)\
                .sample(
                    region=region,
                    scale=10,
                    factor=FACTOR_SAMPLES,
                    dropNulls=True,
                    geometries=True,
                    tileScale=16
                )
            
            
            samplesName = '{}-{}-{}'.format(gridName, year, OUTPUT_VERSION)

            task = ee.batch.Export.table.toAsset(
                collection=samples,
                description=samplesName,
                assetId='{}/{}'.format(ASSET_OUTPUT, samplesName),
            )

            print('Exporting {}...'.format(samplesName))

            task.start()
        except Exception as e:
            print(e)
