"""Sentinel Collection 3 stage 4: classify mosaics by grid and year.

This script loads the training tables generated by stage 3, combines Sentinel
mosaic features with annual embedding bands, trains a Random Forest per grid
and year, and exports classification rasters to Earth Engine assets.

Inputs:
- Sentinel-2 mosaic collections filtered by biome and mosaic version
- Training table assets under `.../SAMPLES/AMAZONIA/TRAINED`
- `GOOGLE/SATELLITE_EMBEDDING/V1/ANNUAL` for each processed year

Outputs:
- Classification assets under `.../GENERAL/classification-amz`

Run this after stage 3 and before the temporal filter in stage 5. The
single-class fallback is intentional and should be preserved to avoid
classifier failures on homogeneous tiles.
"""
import ee
import pandas as pd

pd.set_option('mode.chained_assignment', None)

ee.Initialize(project='mapbiomas-colombia')

ASSET_MOSAICS = [
    'projects/nexgenmap/MapBiomas2/SENTINEL/mosaics-3',
    'projects/mapbiomas-mosaics/assets/SENTINEL/BRAZIL/mosaics-3'
    ]

ASSET_SAMPLES = 'projects/mapbiomas-brazil/assets/LAND-COVER-10M/COLLECTION-3/SAMPLES/AMAZONIA/TRAINED'

ASSET_OUTPUT = 'projects/mapbiomas-brazil/assets/LAND-COVER-10M/COLLECTION-3/GENERAL/classification-amz'

AREAS_TABLE = './data/areas-sentinel-2.csv'

EMBEDDING_COLLECTION = ee.ImageCollection('GOOGLE/SATELLITE_EMBEDDING/V1/ANNUAL')

YEARS = [
    2017,
    2018,
    2019,
    2020,
    2021,
    2022,
    2023,
    2024,
    2025,
    # 2016,
]

SAMPLES_VERSION = '1'

# versao 1 - primeiro teste para a coleção 3 com embedding
# versao 2 - sem usar embedding
OUTPUT_VERSION = '1'

MOSAIC_VERSION = '3'

RF_PARAMS = {
    'numberOfTrees': 50,
    # 'variablesPerSplit': 4,
    # 'minLeafPopulation': 25
}

FEAT_SPACE_BANDS = [
    "blue_median", 
    "blue_median_wet", 
    "blue_median_dry", 
    "blue_stdDev",
    "green_median", 
    "green_median_dry", 
    "green_median_wet", 
    "green_median_texture",
    "green_min", 
    "green_stdDev",
    "red_median", 
    "red_median_dry", 
    "red_min", 
    "red_median_wet", 
    "red_stdDev",
    "nir_median", 
    "nir_median_dry", 
    "nir_median_wet", 
    "nir_stdDev",
    "red_edge_1_median",
    "red_edge_1_median_dry", 
    "red_edge_1_median_wet", 
    "red_edge_1_stdDev",
    "red_edge_2_median",
    "red_edge_2_median_dry", 
    "red_edge_2_median_wet", 
    "red_edge_2_stdDev",
    "red_edge_3_median",
    "red_edge_3_median_dry", 
    "red_edge_3_median_wet", 
    "red_edge_3_stdDev",
    "red_edge_4_median",
    "red_edge_4_median_dry", 
    "red_edge_4_median_wet", 
    "red_edge_4_stdDev",
    "swir1_median", 
    "swir1_median_dry", 
    "swir1_median_wet", 
    "swir1_stdDev",
    "swir2_median", 
    "swir2_median_wet", 
    "swir2_median_dry", 
    "swir2_stdDev"
]

EMBEDDING_BANDS = [
    "A00",
    "A01",
    "A02",
    "A03",
    "A04",
    "A05",
    "A06",
    "A07",
    "A08",
    "A09",
    "A10",
    "A11",
    "A12",
    "A13",
    "A14",
    "A15",
    "A16",
    "A17",
    "A18",
    "A19",
    "A20",
    "A21",
    "A22",
    "A23",
    "A24",
    "A25",
    "A26",
    "A27",
    "A28",
    "A29",
    "A30",
    "A31",
    "A32",
    "A33",
    "A34",
    "A35",
    "A36",
    "A37",
    "A38",
    "A39",
    "A40",
    "A41",
    "A42",
    "A43",
    "A44",
    "A45",
    "A46",
    "A47",
    "A48",
    "A49",
    "A50",
    "A51",
    "A52",
    "A53",
    "A54",
    "A55",
    "A56",
    "A57",
    "A58",
    "A59",
    "A60",
    "A61",
    "A62",
    "A63"
]

GRID_NAMES = []

#
#
#

collection = (
    ee.ImageCollection(ASSET_MOSAICS[0]).merge(ee.ImageCollection(ASSET_MOSAICS[1]))
    .filter(ee.Filter.eq('version', MOSAIC_VERSION))
    .filter(ee.Filter.eq('biome', 'AMAZONIA'))
    )

if len(GRID_NAMES) == 0:
    # Empty GRID_NAMES means "classify every grid available in the mosaics".
    GRID_NAMES = collection.aggregate_histogram('grid_name').getInfo().keys()

print(GRID_NAMES)

alreadyInCollection = ee.ImageCollection(ASSET_OUTPUT) \
    .filterMetadata('version', 'equals', OUTPUT_VERSION) \
    .reduceColumns(
        ee.Reducer.toList(),
        ['system:index']) \
    .get('list').getInfo()

for year in YEARS:

    collectionYear = collection.filter('year == {}'.format(year))

    # Keep the classifier input schema aligned with stage 3 sample extraction.
    embeddingImage = ee.Image(EMBEDDING_COLLECTION
      .filterDate(f'{year}-01-01', f'{year}-12-31')
      .mosaic())
    
    for gridName in GRID_NAMES:

        imageName = '{}-{}-{}'.format(gridName, year, OUTPUT_VERSION)

        # Skip exports that already exist for this versioned grid/year output.
        if imageName not in alreadyInCollection:
            try:
                samplesName = '{}/{}-{}-{}'.format(ASSET_SAMPLES,
                                                gridName, year, SAMPLES_VERSION)

                image = collectionYear.filterMetadata(
                    'grid_name', 'equals', gridName).first()

                image = ee.Image(image)
                
                composite = image.addBands(embeddingImage)

                # Expand the export region slightly to avoid edge clipping on tile bounds.
                geometry = image.geometry().buffer(300).bounds()
                
                samples = ee.FeatureCollection(samplesName)

                print('n samples:', samples.size().getInfo())

                classHistogram = samples.aggregate_histogram('class').getInfo()

                if len(classHistogram) == 1:
                    # smileRandomForest requires >=2 classes ("Only one class" error).
                    # Tiles that are 100% one stable class (e.g. homogeneous primary
                    # forest) get that class assigned directly instead of a classifier.
                    singleClass = int(list(classHistogram.keys())[0])

                    # cast to match classify()'s default int32 output type, so this
                    # collection stays homogeneous when merged downstream (script 5)
                    classification = ee.Image.constant(singleClass) \
                        .toInt() \
                        .updateMask(composite.select(0).mask()) \
                        .rename('classification')
                else:
                    # Train one RF model per grid and year using spectral + embedding features.
                    classifier = ee.Classifier.smileRandomForest(  # type: ignore
                        numberOfTrees=RF_PARAMS['numberOfTrees']
                    ).train(
                        features=samples,
                        classProperty='class',
                        inputProperties=FEAT_SPACE_BANDS + EMBEDDING_BANDS,
                    )

                    classification = composite.classify(classifier)

                classification = classification\
                    .set('grid_name', gridName)\
                    .set('year', year)\
                    .set('version', OUTPUT_VERSION)

                region = geometry.getInfo()['coordinates']

                task = ee.batch.Export.image.toAsset(
                    image=classification,
                    description=imageName,
                    assetId='{}/{}'.format(ASSET_OUTPUT, imageName),
                    pyramidingPolicy={".default": "mode"},
                    region=region,
                    scale=10,
                    maxPixels=1e13
                )

                print('Exporting {}...'.format(imageName))
                
                task.start()
            except Exception as e:
                print(e)
