"""Sentinel Collection 4 stage 2: extract similarity masks by segment.

This script segments each Sentinel-2 mosaic with SNIC, propagates labels
from previously exported stable sample points to the segment level, validates
segment agreement, and exports per-grid, per-year labeled masks.

Inputs:
- Sentinel-2 mosaic collections filtered by biome and mosaic version
- Stable map asset and stable point assets generated by stage 1

Outputs:
- Segment-label assets under `.../SAMPLES/AMAZONIA/SEGMENTS`

Run this after stage 1 and before stage 3. Keep `N_SAMPLES`,
`STABLE_VERSION`, `MOSAIC_VERSION`, `OUTPUT_VERSION`, and `GRID_NAMES`
aligned with the upstream assets you intend to consume.
"""
import ee
from pprint import pprint

ee.Initialize(project='mapbiomas-colombia')

ASSET_MOSAICS = [
    'projects/nexgenmap/MapBiomas2/SENTINEL/mosaics-3',
    'projects/mapbiomas-mosaics/assets/SENTINEL/BRAZIL/mosaics-3'
    ]

ASSET_STABLE_POINTS = 'projects/mapbiomas-brazil/assets/LAND-COVER-10M/COLLECTION-3/SAMPLES/AMAZONIA/POINTS'

ASSET_OUTPUT = 'projects/mapbiomas-brazil/assets/LAND-COVER-10M/COLLECTION-3/SAMPLES/AMAZONIA/SEGMENTS'

ASSET_MAPBIOMAS = 'projects/mapbiomas-public/assets/brazil/lulc/collection10_1/mapbiomas_brazil_collection10_1_coverage_v1'

ASSET_STABLE = 'projects/mapbiomas-brazil/assets/LAND-COVER-10M/COLLECTION-3/SAMPLES/AMAZONIA/AMAZONIA-STABLE-1'

N_SAMPLES = 1000

YEARS = [
    2016,
    2017,
    2018,
    2019,
    2020,
    2021,
    2022,
    2023,
    2024,
    2025
]

MOSAIC_VERSION = '3'

STABLE_VERSION = '1'

# versao 1 - amostras sorteadas no mapa estavel com 1000 pontos
OUTPUT_VERSION = '1'

GRID_NAMES = [
    "NA-20-V-A",
    "NB-20-Y-C",
    "NB-20-Y-D",
    "SB-18-Z-A",
    "SC-18-X-A"
]

collection = (
    ee.ImageCollection(ASSET_MOSAICS[0])
    .merge(ee.ImageCollection(ASSET_MOSAICS[1]))
    .filter(ee.Filter.eq('version', MOSAIC_VERSION))
    .filter(ee.Filter.eq('biome', 'AMAZONIA'))
)

print(collection.size().getInfo())

stable = ee.Image(ASSET_STABLE)

if len(GRID_NAMES) == 0:
    GRID_NAMES = collection.aggregate_histogram('grid_name').getInfo().keys()

print(GRID_NAMES)

SEGMENT_BANDS = [
    "blue_median",
    "green_median",
    "red_median",
    "nir_median",
    "swir1_median",
    "swir2_median"
]


def getSegments(image, size=16):
    """Segment a Sentinel mosaic into SNIC superpixels.

    Args:
        image (ee.Image): Mosaic subset containing the segmentation bands.
        size (int, optional): Seed spacing and base SNIC segment size.

    Returns:
        ee.Image: Single-band image named `segments` with segment ids.
    """

    # Use SNIC superpixels so stable point labels can be propagated by segment.
    seeds = ee.Algorithms.Image.Segmentation.seedGrid(
        size=size,
        gridType='square'
    )

    snic = ee.Algorithms.Image.Segmentation.SNIC(
        image=image,
        size=size,
        compactness=1,
        connectivity=8,
        neighborhoodSize=2*size,
        seeds=seeds
    )

    snic = ee.Image(snic)

    # .copyProperties(image)
    # .copyProperties(image, ['system:footprint'])
    # .copyProperties(image, ['system:time_start'])
    return snic.select(['clusters'], ['segments'])


def getSimilarMask(segments, samples, prop):
    """Project sample labels from points onto segment ids.

    Args:
        segments (ee.Image): Segment-id image returned by `getSegments`.
        samples (ee.FeatureCollection): Stable sample points with class labels.
        prop (str): Sample property containing the label to propagate.

    Returns:
        ee.Image: Single-band image named `class` with segment labels.
    """

    # samplesSegments = segments.reduceRegions(
    #     collection=samples,
    #     scale=10,
    #     reducer=ee.Reducer.first(),
    #     tileScale=16
    # )

    samplesSegments = segments.sampleRegions(
        collection=samples,
        properties=[prop],
        scale=10
    )

    segmentsValues = ee.List(
        samplesSegments
        .reduceColumns(
            ee.Reducer.toList().repeat(2),
            [prop, 'segments']
        ).get('list')
    )

    # Remap segment ids to the stable class observed at sampled locations.
    similiarMask = segments.remap(
        segmentsValues.get(1),
        segmentsValues.get(0), 0)

    return similiarMask.rename(['class'])


for year in YEARS:

    collectionYear = collection.filterMetadata('year', 'equals', year)

    for gridName in GRID_NAMES:
        image = collectionYear.filter(
            ee.Filter.eq('grid_name', gridName))
        # print(image.size().getInfo())
        image = ee.Image(image.first())

        region = image.geometry()
        # print(region.getInfo())

        samples = ee.FeatureCollection(
            '{}/{}-STABLE-{}-{}'.format(ASSET_STABLE_POINTS, gridName, N_SAMPLES, STABLE_VERSION))
        # print(samples.size().getInfo())
        segments = getSegments(image.select(SEGMENT_BANDS), 16)

        similarMask = getSimilarMask(
            segments, samples, prop='stable')

        # Keep only segments whose stable labels are internally consistent.
        percentil = segments.addBands(stable, ['stable'])\
            .reduceConnectedComponents(ee.Reducer.percentile([5, 95]), 'segments')

        validated = segments.addBands(stable, ['stable'])\
            .reduceConnectedComponents(ee.Reducer.mode(), 'segments')

        validated = validated.multiply(
            percentil.select(0).eq(percentil.select(1)).eq(1))

        similarMaskValidated = similarMask.mask(
            similarMask.eq(validated)).rename('class')

        samplesName = '{}-SEGMENTS-{}-{}-{}'.format(
            gridName, year, N_SAMPLES, OUTPUT_VERSION)

        print('Exporting {}...'.format(samplesName))

        task = ee.batch.Export.image.toAsset(
            image=similarMaskValidated.selfMask(),
            description=samplesName,
            assetId='{}/{}'.format(ASSET_OUTPUT, samplesName),
            pyramidingPolicy={".default": "mode"},
            region=region,
            scale=10,
            maxPixels=1e13
        )

        task.start()
